# https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/suborg.yml
---
suborgrepos:
  - '*'

rulesets:
  - name: Base Rulesets
    target: branch
    enforcement: active
    bypass_actors:
      - actor_id: 1
        actor_type: OrganizationAdmin
        bypass_mode: always

      - actor_id: 1097369
        actor_type: Integration
        bypass_mode: pull_request

      - actor_id: 11825178
        actor_type: Team
        bypass_mode: pull_request

    conditions:
      ref_name:
        include:
          - "refs/heads/rhoai-*"
        exclude: []

    rules:
      - type: deletion

      - type: non_fast_forward

      - type: pull_request
        parameters:
          required_approving_review_count: 0
          dismiss_stale_reviews_on_push: false
          require_code_owner_review: false
          require_last_push_approval: false
          required_review_thread_resolution: false
          allowed_merge_methods:
            - merge
            - squash
            - rebase
