# https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/sample-deployment-settings.yml
---
restrictedRepos:  
  exclude:
    - 'admin'
  # include:
  #   - '^rhods-operator$'
