# https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/suborg.yml
---
repository:
  name: rhods-operator

# rulesets:
#   - name: Base Rulesets
#     target: branch
#     enforcement: active
#     bypass_actors:
#       - actor_id: 11825178
#         actor_type: Team
#         bypass_mode: pull_request

#     conditions:
#       ref_name:
#         include:
#           - "refs/heads/rhoai-*"
#         exclude: []

#     rules:
#       - type: creation

#       - type: non_fast_forward

#       - type: pull_request
#         parameters:
#           required_approving_review_count: 1
#           dismiss_stale_reviews_on_push: true
#           require_code_owner_review: false
#           require_last_push_approval: false
#           required_review_thread_resolution: false
#           allowed_merge_methods:
#             - merge
#             - squash
#             - rebase

branches:
  # If the name of the branch value is specified as `default`, then the app will create a branch protection rule to apply against the default branch in the repo
  - name: default
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 4
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: false
        # Whether the most recent reviewable push must be approved by someone other than the person who pushed it.
        require_last_push_approval: false
        # Allow specific users, teams, or apps to bypass pull request requirements. Set to null to disable.
        bypass_pull_request_allowances:
          apps: []
          users: []
          teams: []
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks: null
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: ['safe-settings-app-01','konflux-staging']
        users: ['riprasad']
        teams: []
